module.exports = {
	'/' : {
		'viewType': 'home',
	    'pageName': 'home_page',
	    'category': 'home',
	},
	'/items' : {
		'viewType': 'listing',
	    'pageName': 'listing_',
	    'category': '',
	    'subcategory': '',
	},
	'/items/id' : {
		'viewType': 'item_page',
	    'pageName': 'detail_page',
	    'category': '',
	    'subcategory': '',
	    'geo1': '',
	    'geo2': '',
	    'ad_category': '',
	    'ad_subcategory': '',
	    'ad_id': '',
	    'ad_photo': '',
	    'poster_id': '',
	    'poster_type': '',
	    'posting_to_action': '',
	    'action_type': 'loaded',
	},
	'/interstitial' : {
		'viewType': 'interstitial',
	    'pageName': 'interstitial',
	    'category': 'static',
	    'subcategory': '',
	},
	'/categories' : {
		'viewType': 'categoryList',
	    'pageName': 'listing_',
	    'category': '',
	    'subcategory': '',
	},
};