'use strict';

module.exports = {
    'categories#list': 'index',
    'categories#show': 'list',
    'categories#show#listing': 'list',
    'items#search#filters': 'list',
    'items#search': 'list',
    'items#search#nfFilters': 'list',
    'items#search#nf': 'list',
    'items#show': 'item_page',
    'items#map': 'item_page/map',
    'items#gallery': 'item_page/gallery',
    'items#reply': 'item_page/reply',
    'items#success': 'item_page/success',
    'locations#list': 'select_location',
    'post#location': 'posting_step1',
    'post#categories': 'posting_step2',
    'post#subcategories': 'posting_step3',
    'post#form': 'posting_form',
    'post#flow': 'posting_flow',
    'post#edit': 'edititem',
    'post#success': 'posting_success',
    'pages#terms': 'static/terms',
    'pages#help': 'static/help',
    'pages#interstitial': 'static/interstitial',
    'pages#error': 'error'
    'users#register': 'register',
    'users#login': 'login',
    'users#myads': 'myolx/yourads',
    'users#favorites': 'myolx/favoritelisting',
};
